import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def test_v12_release_metadata_is_consistent() -> None:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    lock = tomllib.loads((ROOT / "uv.lock").read_text(encoding="utf-8"))
    locked_project = next(
        package for package in lock["package"] if package["name"] == project["project"]["name"]
    )
    changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    prd = (ROOT / "doc" / "PRD.md").read_text(encoding="utf-8")
    release_workflow = (ROOT / ".github" / "workflows" / "release.yml").read_text(
        encoding="utf-8"
    )
    release_notes = (ROOT / "doc" / "releases" / "v1.2.0.md").read_text(encoding="utf-8")
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    docs_index = (ROOT / "doc" / "README.md").read_text(encoding="utf-8")

    assert project["project"]["version"] == "1.2.0"
    assert locked_project["version"] == "1.2.0"
    assert "## [1.2.0] - 2026-08-13" in changelog
    assert "**文档版本：** V1.2" in prd
    assert "**项目状态：** V1.2.0 Released" in prd
    assert "tags:" in release_workflow
    assert "contents: write" in release_workflow
    assert 'gh release create "$GITHUB_REF_NAME"' in release_workflow
    assert "# VectorDeckPPT v1.2.0" in release_notes
    assert "[V1.2 Release](doc/releases/v1.2.0.md)" in readme
    assert "[V1.2.0](releases/v1.2.0.md)" in docs_index
    unreleased_link = (
        "[Unreleased]: "
        "https://github.com/AaaBinfinity/VectorDeckPPT/compare/v1.2.0...HEAD"
    )
    assert unreleased_link in changelog


def test_requirements_export_is_reproducible_and_portable() -> None:
    content = (ROOT / "requirements.txt").read_text(encoding="utf-8")

    assert content.startswith("# This file was autogenerated by uv")
    assert "--no-emit-project" in content.splitlines()[1]
    assert str(ROOT).lower() not in content.lower()
