import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def test_v11_release_metadata_is_consistent() -> None:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    lock = tomllib.loads((ROOT / "uv.lock").read_text(encoding="utf-8"))
    locked_project = next(
        package for package in lock["package"] if package["name"] == project["project"]["name"]
    )
    changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    prd = (ROOT / "doc" / "PRD.md").read_text(encoding="utf-8")
    release_workflow = (ROOT / ".github" / "workflows" / "release.yml").read_text(
        encoding="utf-8"
    )
    release_notes = (ROOT / "doc" / "releases" / "v1.1.0.md").read_text(encoding="utf-8")

    assert project["project"]["version"] == "1.1.0"
    assert locked_project["version"] == "1.1.0"
    assert "## [1.1.0] - 2026-08-09" in changelog
    assert "**文档版本：** V1.1" in prd
    assert "**项目状态：** V1.1 Released" in prd
    assert "tags:" in release_workflow
    assert "contents: write" in release_workflow
    assert 'gh release create "$GITHUB_REF_NAME"' in release_workflow
    assert "# VectorDeckPPT v1.1.0" in release_notes


def test_requirements_export_is_reproducible_and_portable() -> None:
    content = (ROOT / "requirements.txt").read_text(encoding="utf-8")

    assert content.startswith("# This file was autogenerated by uv")
    assert "--no-emit-project" in content.splitlines()[1]
    assert str(ROOT).lower() not in content.lower()
